# Generated by Django 4.1.7 on 2023-03-21 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tablename', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TableSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TableFieldSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('field_type', models.CharField(choices=[('string', 'string'), ('number', 'number'), ('boolean', 'boolean')], max_length=16)),
                ('table_schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_fields', to='tableBuilder.tableschema')),
            ],
        ),
    ]
