# Generated by Django 4.1.7 on 2023-03-21 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableBuilder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablefieldschema',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
