# Generated by Django 4.1.7 on 2023-03-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableBuilder', '0002_alter_tablefieldschema_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='moustafa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='tableBuilder_moustafa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
