# Generated by Django 4.1.7 on 2023-03-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableBuilder', '0003_moustafa_tablebuilder_moustafa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='moustafa',
        ),
        migrations.DeleteModel(
            name='tableBuilder_moustafa',
        ),
        migrations.AlterField(
            model_name='tablefieldschema',
            name='field_type',
            field=models.CharField(choices=[('boolean', 'boolean'), ('string', 'string'), ('number', 'number')], max_length=16),
        ),
    ]
